### ISSUE TITLE
When will the NPM package be released

### ISSUE THREAD

**Issue by summergan** [reportportal/agent-js-jest#1]
I can't find it on NPM。

**Comment by trannguyenhung011086** [comment]
Me too. I cannot install using npm as instructed.

**Comment by leandroeo** [comment]
I`m facing the same problem, did someone discover any workaround for that?

**Comment by kerly** [comment]
+ 1 for NPM package
Only workaround I could find was to clone it and publish it to my own artificatory repository.

**Comment by leandroeo** [comment]
@ringods I've started one pull request contribution to fix one of the issues already reported.
Report Portal lists your repository as "official" contributor, can you evaluate the PR?

**Comment by kerly** [comment]
@leandroeo It sounds like he isn't interested in supporting this repository anymore. Maybe it makes the most sense to create a different repository with your changes, if you're willing to support it, and create the npm package.

**Comment by avarabyeu** [comment]
Guys, we're going to release the package this/next week. I'll keep you posted and close the issue as soon as we have the package in NPM

**Comment by avarabyeu** [comment]
@kerly @summergan @trannguyenhung011086 @leandroeo @ringods 
guys, does anyone have a clue of who is owner of the package:
https://www.npmjs.com/package/reportportal-agent-jest

**Comment by ringods** [comment]
@avarabyeu I suggest you ignore that package and deploy your own in a separate npm scope: `@reportportal/agent-jest`

See the docs for npm scopes: https://docs.npmjs.com/misc/scope

**Comment by avarabyeu** [comment]
@reportportal/reportportal-agent-jest@1.0.3
