### ISSUE TITLE
Self signed cerfiticate error

### ISSUE THREAD

**Issue by lanmeh** [reportportal/agent-js-jest#103]
Hey @AmsterGet, I saw here https://github.com/reportportal/client-javascript/issues/102 you already fixed this issue, can we get an update on this agent as well?

**Comment by AmsterGet** [comment]
Hello @lanmeh !
You are right, the issue already fix and according to https://github.com/reportportal/client-javascript#settings and https://github.com/reportportal/agent-js-jest#rest-client-config you already can use it. This is available from version [5.0.3](https://github.com/reportportal/agent-js-jest/releases/tag/v5.0.3).

**Comment by lanmeh** [comment]
My mistake, thanks for the quick response and clearing up confusion!
