### ISSUE TITLE
Cannot find module '../../../jest/node_modules/jest-cli/build/reporters/base_reporter'

### ISSUE THREAD

**Issue by tmort93** [reportportal/agent-js-jest#12]
## Current Behavior
Executing tests results in the following exception:
```
Error: An error occurred while adding the reporter at path "...\TestApp\node_modules\@reportportal\reportportal-agent-jest\index.js".Cannot find module '../../../jest/node_modules/jest-cli/build/reporters/base_reporter'
    at reporters.forEach.reporter (...\TestApp\node_modules\@jest\core\build\TestScheduler.js:462:15)
    at Array.forEach (<anonymous>)
    at TestScheduler._addCustomReporters (...\TestApp\node_modules\@jest\core\build\TestScheduler.js:450:15)
    at TestScheduler._setupReporters (...\TestApp\node_modules\@jest\core\build\TestScheduler.js:427:12)
    at new TestScheduler (...\TestApp\node_modules\@jest\core\build\TestScheduler.js:172:10)
    at ...\TestApp\node_modules\@jest\core\build\runJest.js:404:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (...\TestApp\node_modules\@jest\core\build\runJest.js:150:24)
    at _next (...\TestApp\node_modules\@jest\core\build\runJest.js:170:9)
```
## Possible Explanation
The path to `base_reporter` appears to have changed somewhere between releases **23.6.0** and **24.0.0** of Jest (there are 10+ alpha releases in there and I didn't feel like checking them all).

## Possible Solutions
Change 
`const base_reporter = require('../../../jest/node_modules/jest-cli/build/reporters/base_reporter');`
in **jestUtils.js** to 
`const base_reporter = require('../../../@jest/reporters/build/base_reporter');` 
This of course will break anyone using version <=23.6.0 of Jest.

OR

If you are interested in backwards compatibility you could import some module like fs or path and simply check both paths to determine where the file is located before requiring it.
 
I'd be happy to submit a pull request if you'd like.

## Steps to Reproduce
1. Complete the [Getting Started](https://jestjs.io/docs/en/getting-started) section using npm (this pretty much just installs jest, adds a .js and a .test.js file and then runs the test).
2. Follow the README for [this repository](https://github.com/reportportal/agent-js-jest)
3. Execute `npm run test`

**Comment by DzmitryHumianiuk** [comment]
@tmort93 plz send us pull request

**Comment by tmort93** [comment]
@DzmitryHumianiuk I submitted a pull request ~7 days ago. Is there anything else you need from me?

**Comment by DzmitryHumianiuk** [comment]
@tmort93 
ppl assigner for review
#13
