### ISSUE TITLE
extendTestDescriptionWithLastError option

### ISSUE THREAD

**Issue by PodarDelia** [reportportal/agent-js-jest#136]
Hello! 

For agent-js-playwright there is extendTestDescriptionWithLastError option. It can be added here too?
Option description: If set to true the last error log will be attached to the test case description and reported on the error log level

Thanks!

**Comment by AmsterGet** [comment]
Hello @PodarDelia !
Thanks for your request!
Technically this is possible and I have already added the task to our backlog!
Could you describe your use case?
If I understand correctly, you prefer to view the latest error log without drilling down to the test case log level.
We just want to understand if it is useful to keep this or similar functionality in future versions of ReportPortal.

**Comment by PodarDelia** [comment]
Here is an screenshot from our playwright project where de Error is visible in description
![Screenshot 2024-01-23 at 13 46 23](https://github.com/reportportal/agent-js-jest/assets/48274076/d7f86987-4334-4c84-b3b1-fbdc1895937a)

Here is and screenshot from our jest project where the error is not visible and I have to click on test to see the issue
![Screenshot 2024-01-23 at 13 47 07](https://github.com/reportportal/agent-js-jest/assets/48274076/ff8e372c-87a7-4c7a-a95a-2b779fa04a53)

It is easier to see all the errors on one page than clicking on every failed tests to see the error. When there is a lot of tests that are failing it is very useful to see an overview of the results.

**Comment by AmsterGet** [comment]
Hello @PodarDelia !
Released in version [5.1.0](https://github.com/reportportal/agent-js-jest/releases/tag/v5.1.0).
Please check it out.
