### ISSUE TITLE
Can't set Debug flag

### ISSUE THREAD

**Issue by navisayslisten** [reportportal/agent-js-jest#16]
There doesn't seem to be a way to set debug=true like I can with other report portal agents.

I have tried setting it in:
 - jest.config.js
 - With .env flag (I'm assuming, "RP_DEBUG=true")

```
...
reporters: [
        "default",
        [
            "@reportportal/reportportal-agent-jest",
            {
                "endpoint": "https://report-portal.myurl.io/api/v1",
                "project": "myproject",
                "launchname": "myproject-unit-test",
                "tags": ["cog","unit","react","jest"],
                "debug": true
            }
        ]
    ],
...
```

Neither method sends test results to the debug view.

**Comment by jay-ncino** [comment]
Wondering if there are any updates on this?

**Comment by navisayslisten** [comment]
I have since moved on after no longer using Report Portal. This issue never got addressed or resolved.
