### ISSUE TITLE
The reporter config should include a timeout

### ISSUE THREAD

**Issue by orende** [reportportal/agent-js-jest#18]
If the endpoint of the reportportal agent doesn't respond, the agent could cause a build to hang for a long time. It should be possible to specify a maximum timeout for the agent after which it gives up trying to submit the report and either logs a warning or throws an error.

**Comment by AmsterGet** [comment]
This feature was released in [5.0.3](https://github.com/reportportal/agent-js-jest/releases/tag/v5.0.3).
You may specify necessary timeout (default is 30000 ms) via `restClientConfig.timeout` proprety for reporter config (more details if [client-javascript](https://github.com/reportportal/client-javascript#timeout-30000ms-on-axios-requests) docs).
