### ISSUE TITLE
Receiving Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by cpothier** [reportportal/agent-js-jest#21]
I have report portal up and running on port 8080. I can login to the UI. Per the documents I've added the following config to jest.config.js:

`["@reportportal/reportportal-agent-jest",
                  {
                    "token": "2ab677f5-1ca2-49eb-b50b-c7e947b22648",
                    "endpoint": "http://localhost:8080/api/v1",
                    "launchname": "superadmin_TEST_EXAMPLE",
                    "project": "user_service"
                  }
                ]`

On my test run script i execute the following:
`npx jest --reporters=@reportportal/reportportal-agent-jest`

When the script is run I am receiving the following errors:

`{ Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }`

Not certain why it is trying to hit port 80 instead of 8080. So i tried changing the endpoint to something random like https://testing@reportportaljest.com:8080 and it still tries to hit 127.0.0.1:80. So it seems like its not picking up my jest config parameters. I've also tried changing from https to http. Still no difference. Any idea how to troubleshoot this?

**Comment by saurabhxkapoor** [comment]
I am also facing the same issue. Any resolution on this ?

**Comment by javieratorresm** [comment]
Are you working with .env files? I fix the same problem caused by the missing .env by the gitignore for Github in the project

**Comment by KatsiarynaTatarynovich** [comment]
Hi @cpothier

**Comment by evjlobanova** [comment]
Please reopen if it is still actual

**Comment by sharmadeepak43** [comment]
I am also facing the same issue - Fail to finish test Error: connect ECONNREFUSED 127.0.0.1:80
    at ../../../node_modules/@reportportal/client-javascript/lib/rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Can someone please take a look into it.

**Comment by baradhiren** [comment]
I was facing the same issue with mocha-multi-reporter.
Turns out I had a typo in reporter option attribute in the config file used for reporter options.
It should be `reportportalAgentJsMochaReporterOptions` instead I was using `agentJsMochaReporterOptions`.

**Comment by saritvakrat** [comment]
I still encounter this issue, any idea why?

`const { defineConfig } = require('cypress');
const registerReportPortalPlugin = require('@reportportal/agent-js-cypress/lib/plugin');
const legacyPlugins = require('./cypress/plugins');

module.exports = defineConfig({
  defaultCommandTimeout: 10000,
  requestTimeout: 10000,
  reporter: 'cypress-multi-reporters',
  reporterOptions: {
    endpoint: 'http://xxxxx:8080/api/v1',
    token: '-',
    launch: `${process.env.JOB_NAME || 'GB-UI-Manual'}`,
    project: '--al',
    description: `Build by ${process.env.USER || process.env.USERNAME}${process.env.BUILD_NUMBER ? `. Build number - ${process.env.BUILD_NUMBER}` : ''} `,
    mode: 'DEFAULT', //  "mode": "DEBUG", == print data into userdebug section and not to the launch
    rerun: false,
    skippedIssue: true, // TRUE = 'To Investigate'.FALSE - skipped tests will not be marked as 'To Investigate',
    debug: true, // useful for debugging report-portal - SHOULD BE disabled
    parallel: true, // Indicates to the reporter that spec files will be executed in parallel.
    autoMerge: true, // Automatically merge launches
    // attributes: [
    //   {
    //     key: 'attributeKey',
    //     value: 'attrbiuteValue',
    //   },
    //   {
    //     value: 'anotherAttrbiuteValue',
    //   },
    // ],
    reporterEnabled: 'mocha-junit-reporter,cypress-mochawesome-reporter,@reportportal/agent-js-cypress',
    mochaJunitReporterReporterOptions: {
      mochaFile: 'results/mocha-junit/results-[hash].xml',
      outputs: true,
      includePending: true,
    },
    cypressMochawesomeReporterReporterOptions: {
      reportDir: 'results/mochawesome-report',
      charts: true,
      overwrite: true,
      html: true,
      json: true
    },
  },
  retries: {
    runMode: 1,
    openMode: 0,
  },
  experimentalStudio: true,
  viewportWidth: 1280,
  viewportHeight: 900,
  video: false,
  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      registerReportPortalPlugin(on, config);
      return legacyPlugins(on, config);
    },
    baseUrl: '---',
    excludeSpecPattern: ['**/__snapshots__/*', '**/__image_snapshots__/*'],
    experimentalRunAllSpecs: true
  }
});
`
