### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by Arbarwings** [reportportal/agent-js-jest#43]
When will the NPM package get updated to the latest version as in this Github repository?

**Comment by KatsiarynaTatarynovich** [comment]
Hi @Arbarwings 
We have just released the new version of the jest reporter as a new package @reportportal/agent-js-jest: https://www.npmjs.com/package/@reportportal/agent-js-jest.
It's fully compatible with ReportPortal version 5.*
The package @reportportal/reportportal-agent-jest is deprecated now.
