### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by mmdc88** [reportportal/agent-js-jest#45]
Hi, will this repo be continued? Any plans for updating the npm package?
If not, do you mind if my team proceed creating the new package?

**Comment by mmdc88** [comment]
we created a circleci conf to use this as is
our fork is here https://github.com/mmdc88/agent-js-jest
and the updated pkg is here https://www.npmjs.com/package/@npmcitteam/reportportal-agent-jest
we will probably take a look on the unit tests failing, if you have any info da might help us, please let me know

**Comment by KatsiarynaTatarynovich** [comment]
Hi @mmdc88

**Comment by evjlobanova** [comment]
Closed due to no answer
