### ISSUE TITLE
token undefined: Not able to use report portal jest agent :(

### ISSUE THREAD

**Issue by amartanwar42** [reportportal/agent-js-jest#46]
Hi Team,
I am not able to use the report portal js agent i am getting the below error 
`> jest --no-colors --detectOpenHandles src/__tests__/api_test.js --config ./jest.config.js

{
  error: 'invalid_token',
  error_description: 'Invalid access token: undefined'
}
{
  error: 'invalid_token',
  error_description: 'Invalid access token: undefined'
}
PASS src/__tests__/api_test.js
  ✓ Overview test (1330 ms)

{
  error: 'invalid_token',
  error_description: 'Invalid access token: undefined'
}
{
  error: 'invalid_token',
  error_description: 'Invalid access token: undefined'
}
{
  error: 'invalid_token',
  error_description: 'Invalid access token: undefined'
}
{
  error: 'invalid_token',
  error_description: 'Invalid access token: undefined'
}
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.987 s, estimated 3 s
Ran all test suites matching /src\/__tests__\/api_test.js/i.
{
  error: 'invalid_token',
  error_description: 'Invalid access token: undefined'
}`

here is jest.config.js
`module.exports = {
  reporters: [
    'default',
    [
      '@reportportal/reportportal-agent-jest',
      {
        token: <token>,
        endpoint: '<end points>',
        project: 'patient_api_automation',
        launch: 'Test',
        description: 'YourDescription',
        attributes: [
          {
            key: 'YourKey',
            value: 'YourValue',
          },
          {
            value: 'YourValue',
          },
        ],
      },
    ],
  ],}`

**Comment by KatsiarynaTatarynovich** [comment]
Hi @amartanwar42 
We have just released the new version of the jest reporter as a new package @reportportal/agent-js-jest: https://www.npmjs.com/package/@reportportal/agent-js-jest.
It's fully compatible with ReportPortal version 5.*
The package @reportportal/reportportal-agent-jest is deprecated now.
I recommend you to try it. I hope this solves your problem.

**Comment by amartanwar42** [comment]
thankyou @KatsiarynaTatarynovich
