### ISSUE TITLE
Error received while integrating with agent - Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Field 'name' should not be null.] "}     at ....\node_modules\@reportportal\client-javascript\lib\rest.js:31:23     at processTicksAndRejections (internal/process/task_queues.js:97:5) 

### ISSUE THREAD

**Issue by AutomationTestEnthusiast** [reportportal/agent-js-jest#60]
I am integrating report portal with reportportal-agent-jest.
When I trigger the tests, I start receiving the error
 Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Field 'name' should not be null.] "}
    at ....\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)  The test results are going to report portal but the launch status gets stuck at In Progress.

RP - v5
jest - v 23.4.2
npm module - @reportportal/agent-js-jest
https://github.com/reportportal/agent-js-jest 

Please find attached a test project by which you can reproduce the issue.  

I also tried by adding the reporter options in package,json in jest but still the results were same. 
[Test Jest project.zip](https://github.com/reportportal/agent-js-jest/files/5447282/Test.Jest.project.zip)

**Comment by philgruneich** [comment]
As you can see, I've opened a PR for this issue.

If you're looking for a quick workaround, wrap your tests in a `describe`, like:

```
describe('sum', () => {
  test('adds 1 + 2 to equal 3', () => {
    expect(sum(1, 2)).toBe(3);
  });
})
```

**Comment by AutomationTestEnthusiast** [comment]
Thanks for providing the workaround and the PR.
