### ISSUE TITLE
Please add support for new config item

### ISSUE THREAD

**Issue by xadvfh** [reportportal/agent-js-jest#77]
`client-javascript` package has added a new config item called `restClientConfig`.  Please add support for this so we can use report portal with self-signed certificates.

**Comment by xadvfh** [comment]
@AmsterGet @KatsiarynaTatarynovich

**Comment by AmsterGet** [comment]
Released in [5.0.3](https://github.com/reportportal/agent-js-jest/releases/tag/v5.0.3).
