### ISSUE TITLE
Duration time under each test suite and test case is always 0s 

### ISSUE THREAD

**Issue by monaboiste** [reportportal/agent-js-jest#80]
Duration time under each test suite and test case is always "0s". Problem is identical as in #17 but it doesn't seem to be related to test execution time being too short. I cloned https://github.com/reportportal/examples-js with example-jest and added test with explicit ``sleep(6000)``. Seems like ``last_modified`` in ``test_item`` table and ``end_time``/``duration`` in ``test_item_results`` in postgresql are updated too soon.
Duration under launches is ok though.

**Comment by oranje322** [comment]
This bug has been fixed https://github.com/reportportal/agent-js-jest/pull/100
Will be released in version 5.0.4

**Comment by geertvanheusden** [comment]
Will `5.0.4` be released soon? Would be great to have this functionality for the Jest tests.
